/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Candle {
  'low' : number,
  'high' : number,
  'close' : number,
  'open' : number,
  'time' : bigint,
  'volume' : number,
}
export interface Derivative {
  'status' : Status,
  'side' : Side,
  'atmOiChange' : [] | [number],
  'itmOiChange' : Array<number>,
  'candles' : Array<Candle>,
  'symbol' : string,
}
export interface Results {
  'disqualified' : Array<Derivative>,
  'ignored' : Array<Derivative>,
  'qualified' : Array<Derivative>,
}
export type Side = { 'long' : null } |
  { 'short' : null };
export type Status = { 'disqualified' : null } |
  { 'ignored' : null } |
  { 'qualified' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllCaches' : ActorMethod<[], undefined>,
  'clearCreds' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLastScanTimestamp' : ActorMethod<[], [] | [Time]>,
  'getResults' : ActorMethod<[], [] | [Results]>,
  'getStatus' : ActorMethod<[], string>,
  'getSymbolList' : ActorMethod<[], [] | [Array<string>]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'runNewScan' : ActorMethod<[], Results>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCreds' : ActorMethod<
    [string, string, string, string, string, Time],
    undefined
  >,
  'saveSymbolList' : ActorMethod<[Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];