/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Status = IDL.Variant({
  'disqualified' : IDL.Null,
  'ignored' : IDL.Null,
  'qualified' : IDL.Null,
});
export const Side = IDL.Variant({ 'long' : IDL.Null, 'short' : IDL.Null });
export const Candle = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'time' : IDL.Int,
  'volume' : IDL.Float64,
});
export const Derivative = IDL.Record({
  'status' : Status,
  'side' : Side,
  'atmOiChange' : IDL.Opt(IDL.Float64),
  'itmOiChange' : IDL.Vec(IDL.Float64),
  'candles' : IDL.Vec(Candle),
  'symbol' : IDL.Text,
});
export const Results = IDL.Record({
  'disqualified' : IDL.Vec(Derivative),
  'ignored' : IDL.Vec(Derivative),
  'qualified' : IDL.Vec(Derivative),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllCaches' : IDL.Func([], [], []),
  'clearCreds' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLastScanTimestamp' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getResults' : IDL.Func([], [IDL.Opt(Results)], ['query']),
  'getStatus' : IDL.Func([], [IDL.Text], ['query']),
  'getSymbolList' : IDL.Func([], [IDL.Opt(IDL.Vec(IDL.Text))], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'runNewScan' : IDL.Func([], [Results], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCreds' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
      [],
      [],
    ),
  'saveSymbolList' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Status = IDL.Variant({
    'disqualified' : IDL.Null,
    'ignored' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const Side = IDL.Variant({ 'long' : IDL.Null, 'short' : IDL.Null });
  const Candle = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'time' : IDL.Int,
    'volume' : IDL.Float64,
  });
  const Derivative = IDL.Record({
    'status' : Status,
    'side' : Side,
    'atmOiChange' : IDL.Opt(IDL.Float64),
    'itmOiChange' : IDL.Vec(IDL.Float64),
    'candles' : IDL.Vec(Candle),
    'symbol' : IDL.Text,
  });
  const Results = IDL.Record({
    'disqualified' : IDL.Vec(Derivative),
    'ignored' : IDL.Vec(Derivative),
    'qualified' : IDL.Vec(Derivative),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllCaches' : IDL.Func([], [], []),
    'clearCreds' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLastScanTimestamp' : IDL.Func([], [IDL.Opt(Time)], ['query']),
    'getResults' : IDL.Func([], [IDL.Opt(Results)], ['query']),
    'getStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getSymbolList' : IDL.Func([], [IDL.Opt(IDL.Vec(IDL.Text))], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'runNewScan' : IDL.Func([], [Results], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCreds' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
        [],
        [],
      ),
    'saveSymbolList' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };